default: "GM3000"

vendor:
  "055c:e618": "GM3000"
  "096e:0309": "GM3000"

## 龙脉 GM3000
GM3000:
  windows: "native\\GM3000\\windows\\mtoken_gm3000.dll"
  linux:  "native/GM3000/linux/libgm3000.1.0.so"
  macos: "native/GM3000/macos/x86_64/libgm3000.1.0.dylib"

## 飞天 3000GM
3000GM:
  windows: "%System32%\\ShuttleCsp11_3000GM.dll"
  linux: "native/3000GM/linux/libes_3000gm.so.1.0.0"
  macos: "native/3000GM/macos/x86_64/libes_3000gm.dylib"

## 渔翁
FISHMAN:
  windows: "native\\FISHMAN\\windows\\KeyGDBApi.dll"
