#!/usr/bin/env node
/**
 * v0.2.0 contract fixture recorder.
 *
 * PURPOSE
 *   Record the responses produced by the **pre-refactor** service so that later
 *   refactoring can be proven behavior-preserving. Fixtures must NEVER be
 *   generated by a fake provider — that would make the regression test a
 *   tautology (CONTEXT.md decision D-10).
 *
 * USAGE
 *   1. Start the service from an UNMODIFIED working tree:
 *        cargo run
 *   2. Run:
 *        node tools/record_fixtures.js --out tests/fixtures/v0.2.0
 *
 * DESIGN NOTES
 *   - Parameter order comes from `api/skf_api.js` (the production client), not
 *     from this script. We only wrap the client to capture raw JSON-RPC frames.
 *   - Each method is recorded on a FRESH connection by default. The server keeps
 *     per-connection language state and process-wide hash handles, so a fresh
 *     connection makes each method's context deterministic.
 *   - Methods whose responses are not deterministic are declared in
 *     VOLATILE_PATHS with a source-level reason. That declaration is frozen at
 *     record time and must not be widened later to make a failing test pass.
 *   - Placeholder parameters are used instead of real credentials. No PIN or key
 *     material is ever written to a fixture.
 */

'use strict';

const fs = require('fs');
const path = require('path');
const WebSocket = require('ws');
const SKFClient = require('../api/skf_api');

global.WebSocket = WebSocket;

// ---------------------------------------------------------------------------
// CLI
// ---------------------------------------------------------------------------

function parseArgs(argv) {
    const out = { out: 'tests/fixtures/v0.2.0', ws: 'ws://127.0.0.1:9001' };
    for (let i = 2; i < argv.length; i++) {
        const a = argv[i];
        if (a === '--out') out.out = argv[++i];
        else if (a === '--ws') out.ws = argv[++i];
        else if (a === '--help' || a === '-h') {
            console.log('usage: node tools/record_fixtures.js [--out DIR] [--ws URL]');
            process.exit(0);
        }
    }
    return out;
}

// ---------------------------------------------------------------------------
// Volatile field declarations (frozen at record time)
// ---------------------------------------------------------------------------

/**
 * Map of method -> { "<json path>": "<marker>" }.
 *
 * The VALUE must be a marker string shaped like `<...>`; only then does
 * `apply_normalize` substitute it. Human-readable justifications live in
 * VOLATILE_REASONS so they never get mistaken for markers.
 *
 * Every entry must be justified by the pre-refactor source, not by a test
 * failure. Paths use dot notation; "result.handle" means response.result.handle.
 */
const VOLATILE_PATHS = {
    ConnectDev: { result: '<volatile:handle>' },
    GenerateRandom: { result: '<volatile:random>' },
    IssueCertificate: { result: '<volatile:certificate>' },
    // Provider list order is process-dependent: the handler iterates a HashMap.
    // '<unordered>' sorts the array so contents stay asserted.
    EnumProvider: { result: '<unordered>' },
};

/** Source-level justification for each declaration above. */
const VOLATILE_REASONS = {
    ConnectDev: {
        'result': 'src/main.rs ConnectDev returns format!("{}", h_dev as usize) — a process-local pointer value',
    },
    GenerateRandom: {
        'result': 'device CSPRNG output is random by definition',
    },
    IssueCertificate: {
        'result': 'src/main.rs IssueCertificate shells out to OpenSSL and generates fresh RSA/SM2 material and certificate serials',
    },
    EnumProvider: {
        'result': 'src/main.rs EnumProvider returns ctx.config.libs.keys(), a HashMap, so the provider list has the same contents in a process-dependent order; compared as a set',
    },
};

/**
 * Static per-method notes explaining what the recording did and did not cover.
 *
 * Notably CheckPIN: the source embeds the token retry counter in the VerifyPIN
 * failure message, but that message was NOT observed here (reaching it needs a
 * token). Declaring `message` volatile would therefore erase a deterministic
 * field and weaken the oracle, so it is asserted verbatim instead.
 */
const RECORDING_NOTES = {
    CheckPIN: 'VerifyPIN failure message was not reached (no token); message is asserted verbatim, not normalized',
};

/** Methods that need a real token to produce their success path. */
const HARDWARE_METHODS = new Set([
    'ConnectDev', 'EnumApplication', 'EnumContainer', 'DeleteContainer',
    'ImportCertificate', 'SignData', 'DisConnectDev', 'FindCertificates',
    'GenerateRandom', 'GetDevInfo', 'SetLabel', 'ECCVerify', 'CreateContainer',
    'GetContainerType', 'RSASignData', 'LockDev', 'UnlockDev', 'Transmit',
    'GenECCKeyPair', 'GenRSAKeyPair', 'RSAVerify', 'Digest', 'DigestInit',
    'DigestUpdate', 'DigestFinal', 'CloseHash', 'CreatePKCS10',
    'EncryptData', 'DecryptData', 'CheckPIN', 'WaitForDevEvent',
]);

// Placeholder parameters — never real device names, containers, or PINs.
const PLACEHOLDER = {
    provider: null,            // resolved from config at run time
    device: '__record_device__',
    app: '__record_app__',
    container: '__record_container__',
    pin: '00000000',
};
const PLACEHOLDER_PARAM_NAMES = ['device', 'app', 'container', 'pin'];

/**
 * Lightweight liveness probe. Returns true when the service answers a trivial
 * request. Used between scenarios so that a service crash produces one clear
 * message instead of a wall of confusing "no response" entries.
 */
async function probe(wsUrl) {
    let client = null;
    try {
        const connected = await connect(wsUrl);
        client = connected.client;
        await client.call('EnumProvider', []);
        return true;
    } catch (_) {
        return false;
    } finally {
        if (client) client.disconnect();
    }
}

// ---------------------------------------------------------------------------
// Raw frame capture
// ---------------------------------------------------------------------------

/**
 * Wrap `client.call` so that both the outgoing request and the raw incoming
 * response envelope are captured, keyed by JSON-RPC id.
 */
function instrument(client) {
    const requests = new Map(); // id -> {jsonrpc, method, params, id}
    const responses = new Map(); // id -> raw response object

    const originalCall = client.call.bind(client);
    client.call = function (method, params = []) {
        const id = this.msgId; // `call` uses this.msgId then increments
        requests.set(id, { jsonrpc: '2.0', method, params, id });
        return originalCall(method, params);
    };

    return {
        requests,
        responses,
        attach() {
            const socket = client.ws;
            if (!socket) throw new Error('instrument.attach() requires a connected client');
            const previous = socket.onmessage;
            socket.onmessage = (event) => {
                try {
                    const parsed = JSON.parse(event.data);
                    if (parsed && typeof parsed.id !== 'undefined') {
                        responses.set(parsed.id, parsed);
                    }
                } catch (_) {
                    /* ignore non-JSON frames */
                }
                if (previous) previous(event);
            };
        },
    };
}

function connect(wsUrl) {
    const client = new SKFClient(wsUrl);
    const tap = instrument(client);
    return client.connect().then(() => {
        tap.attach();
        return { client, tap };
    });
}

/** Invoke a client method, swallowing the rejection so the raw envelope is kept. */
async function attempt(fn) {
    try {
        return { ok: true, value: await fn() };
    } catch (err) {
        return { ok: false, error: err };
    }
}

async function recordCall(client, tap, fn) {
    const id = client.msgId;
    const outcome = await attempt(fn);
    const request = tap.requests.get(id) || null;
    const response = tap.responses.get(id) || null;
    return { id, request, response, outcome };
}

/** Give the event loop a moment so the raw frame lands in the tap. */
const settle = () => new Promise((r) => setTimeout(r, 120));

// ---------------------------------------------------------------------------
// Scenarios
// ---------------------------------------------------------------------------

/**
 * Record a single request on a fresh connection.
 *
 * No preparatory request is issued: the server defaults each connection to
 * English (`Language::EN` in `spawn_ws_client`), and every JSON-RPC id starts
 * at 1. Keeping the target request as the FIRST request on the connection makes
 * the recorded `id` reproduce exactly during replay.
 */
async function scenarioSimple(wsUrl, invoke) {
    const { client, tap } = await connect(wsUrl);
    try {
        const rec = await recordCall(client, tap, () => invoke(client));
        await settle();
        return {
            setup: [],
            request: rec.request,
            response: rec.response,
            note: rec.outcome.ok ? null : `client rejected: ${describe(rec.outcome.error)}`,
        };
    } finally {
        client.disconnect();
    }
}

function describe(err) {
    if (!err) return 'unknown';
    if (typeof err === 'string') return err;
    return err.message || JSON.stringify(err);
}

/** Digest chain: DigestInit then the requested dependent operation. */
async function scenarioDigestChain(wsUrl, which, provider, device) {
    const { client, tap } = await connect(wsUrl);
    try {
        const init1 = await recordCall(client, tap, () =>
            client.digestInit(provider, device, 0x00000001));
        await settle();

        const fromInit = init1.outcome.ok && init1.outcome.value ? init1.outcome.value.handle : null;
        // The handle key is derived from the JSON-RPC id (`format!("hash_{}", id)`),
        // so it is reproducible even when DigestInit itself failed for lack of a
        // token. Using it lets the dependent methods record their unknown-handle
        // contract instead of being skipped entirely (decision D-11).
        const handle = fromInit || `hash_${init1.id}`;
        const note = fromInit
            ? null
            : `DigestInit did not succeed; dependent request issued with the deterministic handle key "${handle}" to record the unknown-handle contract`;

        if (which === 'DigestInit') {
            return { setup: [], request: init1.request, response: init1.response, note: null };
        }

        const data = Buffer.from('SKF fixture data').toString('base64');
        let rec;
        if (which === 'DigestUpdate') {
            rec = await recordCall(client, tap, () => client.digestUpdate(handle, data));
        } else if (which === 'DigestFinal') {
            rec = await recordCall(client, tap, () => client.digestFinal(handle));
        } else {
            rec = await recordCall(client, tap, () => client.closeHash(handle));
        }
        await settle();

        return { setup: [init1.request], request: rec.request, response: rec.response, note };
    } finally {
        client.disconnect();
    }
}

/**
 * WaitForDevEvent blocks the connection that issues it, so cancellation must
 * come from a second connection. Without this, the recorder would hang.
 *
 * The cancel is timing-sensitive: if it arrives before the waiter has actually
 * entered the blocking vendor call, the cancel is lost and the wait never
 * returns. The scenario therefore waits before cancelling and retries when no
 * response was produced, so a stable contract is recorded rather than a coin
 * flip.
 */
async function scenarioWaitForDevEvent(wsUrl, provider) {
    const MAX_ATTEMPTS = 3;
    let last = null;

    for (let attempt = 1; attempt <= MAX_ATTEMPTS; attempt++) {
        const a = await connect(wsUrl);
        let b = null;
        try {
            const id = a.client.msgId;
            // Fire without awaiting: the server's per-connection loop is busy until cancel.
            const pending = attempt2Promise(() => a.client.waitForDevEvent(provider));
            // Give the waiter time to reach the blocking vendor call before cancelling.
            await new Promise((r) => setTimeout(r, 800));

            b = await connect(wsUrl);
            const cancel = await recordCall(b.client, b.tap, () => b.client.cancelWaitForDevEvent());

            const settled = await Promise.race([
                pending,
                new Promise((r) => setTimeout(() => r({ ok: false, error: 'timeout after cancel' }), 8000)),
            ]);
            await settle();

            last = {
                setup: [],
                request: a.tap.requests.get(id) || null,
                response: a.tap.responses.get(id) || null,
                note: `attempt ${attempt}/${MAX_ATTEMPTS}; cancel response: ${cancel.response ? JSON.stringify(cancel.response) : 'none'}; wait outcome: ${settled && settled.ok ? 'resolved' : describe(settled && settled.error)}`,
            };

            if (last.response) {
                last.note += ' | timing-sensitive pair: cancel must arrive after the wait has entered the blocking call';
                return last;
            }
        } finally {
            a.client.disconnect();
            if (b) b.client.disconnect();
        }
    }

    return last;
}

/** Local alias kept explicit so the retry loop reads clearly. */
function attempt2Promise(fn) {
    return attempt(fn);
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

async function main() {
    const args = parseArgs(process.argv);
    const outDir = path.resolve(args.out);

    // Resolve the default provider alias from the service's own config so the
    // fixtures do not hard-code a provider name.
    const configText = fs.readFileSync(path.resolve('config/skf.yaml'), 'utf8');
    const defaultMatch = configText.match(/^default:\s*"?([^"\n]+)"?/m);
    const provider = defaultMatch ? defaultMatch[1].trim() : 'GM3000';
    PLACEHOLDER.provider = provider;

    const wsUrl = args.ws;
    const D = PLACEHOLDER.device;
    const A = PLACEHOLDER.app;
    const C = PLACEHOLDER.container;
    const P = PLACEHOLDER.pin;
    const data = Buffer.from('SKF fixture data').toString('base64');
    const iv = Buffer.alloc(16, 0x11).toString('base64');
    const symKey = Buffer.alloc(16, 0x22).toString('base64');
    const certKey = `${provider}/${D}/${A}/${C}`;
    const devKey = `${provider}/${D}/${A}`;

    const S = (invoke) => () => scenarioSimple(wsUrl, invoke);

    /** method -> () => {setup, request, response, note} */
    const scenarios = {
        SetLanguage: S((c) => c.setLanguage('CN')),

        WaitForDevEvent: () => scenarioWaitForDevEvent(wsUrl, provider),

        EnumProvider: S((c) => c.enumProvider()),

        EnumDevice: S((c) => c.enumDevice(provider)),

        ConnectDev: S((c) => c.connectDev(D)),

        EnumApplication: S((c) => c.enumApplication(provider, D)),

        EnumContainer: S((c) => c.enumContainer(provider, D, A)),

        DeleteContainer: S((c) => c.deleteContainer(provider, D, A, C, P)),

        IssueCertificate: S((c) => c.issueCertificate(MINIMAL_CSR, false)),

        ImportCertificate: S((c) => c.importCertificate(provider, D, A, C, true, '-----BEGIN CERTIFICATE-----\nMIIB\n-----END CERTIFICATE-----')),

        SignData: S((c) => c.signData(certKey, data)),

        DisConnectDev: S((c) => c.disconnectDev(1)),

        FindCertificates: S((c) => c.findCertificates('')),

        // SAFETY: do NOT send a fabricated handle here. Passing an arbitrary
        // integer as a DEVHANDLE reaches the vendor library unchecked and has
        // been observed to KILL THE SERVICE PROCESS (SKF_GenRandom with handle 1
        // crashes inside the GM3000 DLL). The parameter-validation contract is
        // used instead; handle ownership is addressed by RES-01 in Phase 2.
        GenerateRandom: S((c) => c.call('GenerateRandom', [])),

        Digest: S((c) => c.digest(provider, D, data, 'SM3')),

        CheckPIN: S((c) => c.checkPIN(devKey, P)),

        CreatePKCS10: S((c) => c.createPKCS10(provider, D, A, 'CN=Fixture,O=LiuZX,C=CN', 'SM2', 256)),

        EncryptData: S((c) => c.encryptData(certKey, data, iv, 1, symKey)),

        DecryptData: S((c) => c.decryptData(certKey, data, iv, 1, symKey)),

        GetDevInfo: S((c) => c.getDevInfo(provider, D)),

        GetDevState: S((c) => c.getDevState(provider, D)),

        SetLabel: S((c) => c.setLabel(provider, D, '__fixture_label__')),

        ECCVerify: S((c) => c.eccVerify(provider, D, Buffer.alloc(128, 1).toString('base64'), data, Buffer.alloc(128, 2).toString('base64'))),

        CreateContainer: S((c) => c.createContainer(provider, D, A, '__fixture_container__')),

        GetContainerType: S((c) => c.getContainerType(provider, D, A, C)),

        RSASignData: S((c) => c.rsaSignData(certKey, data)),

        LockDev: S((c) => c.lockDev(provider, D, 5000)),

        UnlockDev: S((c) => c.unlockDev(provider, D)),

        Transmit: S((c) => c.transmit(provider, D, Buffer.from([0x00, 0x84, 0x00, 0x00, 0x08]).toString('base64'))),

        CancelWaitForDevEvent: S((c) => c.cancelWaitForDevEvent()),

        GenECCKeyPair: S((c) => c.genECCKeyPair(provider, D, A, C)),

        GenRSAKeyPair: S((c) => c.genRSAKeyPair(provider, D, A, C, 2048)),

        RSAVerify: S((c) => c.rsaVerify(provider, D, Buffer.alloc(256, 3).toString('base64'), data, Buffer.alloc(256, 4).toString('base64'))),

        DigestInit: () => scenarioDigestChain(wsUrl, 'DigestInit', provider, D),
        DigestUpdate: () => scenarioDigestChain(wsUrl, 'DigestUpdate', provider, D),
        DigestFinal: () => scenarioDigestChain(wsUrl, 'DigestFinal', provider, D),
        CloseHash: () => scenarioDigestChain(wsUrl, 'CloseHash', provider, D),
    };

    fs.mkdirSync(outDir, { recursive: true });

    const recordedFrom = process.env.SKF_FIXTURE_SOURCE_COMMIT || 'unknown';
    const recordedAt = new Date().toISOString();

    let ok = 0;
    let incomplete = 0;
    const failures = [];

    for (const [method, run] of Object.entries(scenarios)) {
        process.stdout.write(`  ${method} ... `);

        if (!(await probe(wsUrl))) {
            console.log('ABORTED (service not reachable — it may have crashed on a previous scenario)');
            console.log('');
            console.log(`ABORTED_AT=${method}`);
            console.log(`RECORDED=${ok}`);
            console.log(`INCOMPLETE=${incomplete}`);
            console.log(`ERRORS=${failures.length}`);
            if (failures.length) console.log(JSON.stringify(failures, null, 2));
            process.exitCode = 2;
            return;
        }

        let result;
        try {
            result = await run();
        } catch (err) {
            console.log(`ERROR (${describe(err)})`);
            failures.push({ method, error: describe(err) });
            continue;
        }

        if (!result.request || !result.response) {
            incomplete++;
            console.log(`INCOMPLETE (${result.note || 'no response captured'})`);
        } else {
            ok++;
            console.log('ok');
        }

        const fixture = {
            method,
            setup: result.setup || [],
            request: result.request,
            response: result.response,
            normalize: VOLATILE_PATHS[method] || {},
            provenance: {
                recorded_from: recordedFrom,
                recorded_at: recordedAt,
                platform: `${process.platform}-${process.arch}`,
                provider_alias: provider,
                requires_hardware: HARDWARE_METHODS.has(method),
                observed_with_device: false,
                placeholder_params: PLACEHOLDER_PARAM_NAMES,
                volatile_fields_reviewed: true,
                volatile_reasons: VOLATILE_REASONS[method] || {},
                recording_note: [result.note, RECORDING_NOTES[method]].filter(Boolean).join(' | ') || null,
            },
        };

        fs.writeFileSync(path.join(outDir, `${method}.json`), JSON.stringify(fixture, null, 2) + '\n');
    }

    console.log('');
    console.log(`RECORDED=${ok}`);
    console.log(`INCOMPLETE=${incomplete}`);
    console.log(`ERRORS=${failures.length}`);
    if (failures.length) {
        console.log(JSON.stringify(failures, null, 2));
    }
}

/** A syntactically valid but trivial CSR for the mock issuance path. */
const MINIMAL_CSR = [
    '-----BEGIN CERTIFICATE REQUEST-----',
    'MIIBZTCB/wIBADBSMQswCQYDVQQGEwJDTjESMBAGA1UECAwJQmVpamluZzESMBAG',
    'A1UEBwwJQmVpamluZzELMAkGA1UECgwCT1gxDjAMBgNVBAMMBVRlc3QwWTATBgcq',
    'hkjOPQIBBggqgRzPVQGCLQNCAAT0dm15/jLZK9nR/MQ7vJ0kM+6d5uWX/V2y8vJ8',
    '-----END CERTIFICATE REQUEST-----',
].join('\n');

main().catch((err) => {
    console.error('recorder failed:', err);
    process.exit(1);
});
